export const commonExpenseDescriptions = [
    'Groceries',
    'Gas',
    'Rent',
    'Mortgage',
    'Utilities',
    'Internet',
    'Cell Phone',
    'Car Payment',
    'Car Insurance',
    'Home Insurance',
    'Health Insurance',
    'Life Insurance',
    'Clothing',
    'Entertainment',
    'Eating Out',
    'Travel',
    'Medical',
    'Dental',
    'Vision',
    'Charity',
    'Education',
    'Gifts',
    'Miscellaneous'
];